name: "On PR"

# Runs on every PR commit. When the PR is to merge it into main
on:
  pull_request:
    branches:
      - main

jobs:
  on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
