name: "On Labeled PR"

on:
  pull_request:
    branches:
      - main
    types:
      - labeled

jobs:
  on-labeled-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
