name: Deploy Preview

on:
  issue_comment:
    types: [created, edited]

jobs:
  call-preview-deploy:
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request }}
    permissions:
      pull-requests: write
    uses: ./.github/workflows/preview-comment.workflow_call.yaml
    with:
      pr_number: ${{ github.event.issue.number }}
      repository: ${{ github.repository }}
      comment_id: ${{ github.event.comment.id }}
      comment_body: ${{ github.event.comment.body }}
